name: Sync LeetCode

on:
  workflow_dispatch: # มึงสามารถมากดสั่งให้มันซิงค์เองเมื่อไหร่ก็ได้
  schedule:
    - cron: '0 0 * * *' # บอทจะวิ่งออโต้ให้มึงทุกเที่ยงคืนของทุกวัน

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: '.'
